//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoFinalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados_Servicios
    {
        public int ID { get; set; }
        public string IdEmpleado { get; set; }
        public int IdServicio { get; set; }
        public string Observacion { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
